# Form implementation generated from reading ui file 'Ventana_principal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QIcon


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Algebra Lineal.")
        MainWindow.resize(628, 526)

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 20, 391, 141))
        self.label.setObjectName("label")

        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(130, 160, 351, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.matrices = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.matrices.setObjectName("matrices")
        self.verticalLayout.addWidget(self.matrices)

        self.inversa = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.inversa.setObjectName("inversa")
        self.verticalLayout.addWidget(self.inversa)

        self.determinante = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.determinante.setObjectName("determinante")
        self.verticalLayout.addWidget(self.determinante)

        self.rango = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.rango.setObjectName("rango")
        self.verticalLayout.addWidget(self.rango)

        self.cifrado = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.cifrado.setObjectName("cifrado")
        self.verticalLayout.addWidget(self.cifrado)

        self.pushButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.vectores = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.vectores.setObjectName("vectores")
        self.verticalLayout.addWidget(self.vectores)

        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 50, 91, 81))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("logo.jpeg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def show_matriz():
            print('Matriz')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Algebra Lineal."))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:700;\">Programa Algebra Lineal. </span></p></body></html>"))
        self.matrices.setText(_translate("MainWindow", "Funciones entre Matrices"))
        self.inversa.setText(_translate("MainWindow", "Matriz Inversa"))
        self.determinante.setText(_translate("MainWindow", "Determinante de una Matriz "))
        self.rango.setText(_translate("MainWindow", "Rango de una matriz."))
        self.cifrado.setText(_translate("MainWindow", "Cifrado por matrices."))
        self.pushButton.setText(_translate("MainWindow", "Cadenas de Markov"))
        self.vectores.setText(_translate("MainWindow", "Operaciones con vectores "))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
